### ISSUE TITLE
[Feature Request] Support Full Width Table Like Minimal Theme

### ISSUE THREAD

**Issue by Yaozhuwa** [AnubisNekhet/AnuPpuccin#2]
This theme is very beautiful.  But it doesn't do any optimization for table layout. It'll be more prefect if it support full width table.

[AnuPpuccin](https://github.com/AnubisNekhet/AnuPpuccin)'s table:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/28787183/197399823-98d58eaa-789c-4a96-bfae-051f5787b525.png">

Minimal theme's Full width table.
<img width="769" alt="image" src="https://user-images.githubusercontent.com/28787183/197399791-8802cda6-12d9-47a8-a3ca-57b4a8200e93.png">

**Comment by AnubisNekhet** [comment]
I've added support for full-width tables in the new update, you can access the settings in Layout settings -> Markdown element settings -> Table settings. However, the width is defined in percentages right now, and I plan to change that to a more minimal-like approach with different values of maximum widths, should someone request it in the future.

**Comment by Yaozhuwa** [comment]
Appreciate your fast repsonds~ I've update this theme and set the style setting.
<img width="787" alt="image" src="https://user-images.githubusercontent.com/28787183/197447764-6faf9f46-b1a9-4f09-b440-653479bec327.png">

It seems that the full-width table doesn't work for me. Here is my screenshot of AnuPpuccin:
<img width="834" alt="image" src="https://user-images.githubusercontent.com/28787183/197448085-1d272695-cd8b-45df-9721-ff3d6cf62e83.png">

The Minimal's full width table is shown below
<img width="829" alt="image" src="https://user-images.githubusercontent.com/28787183/197448157-55da6e9e-f277-47eb-a967-bda4844692de.png">

**Comment by AnubisNekhet** [comment]
Can you re-type 100 into the input box?
If it doesn't work I'll add a fallback value.

**Comment by Yaozhuwa** [comment]
> Can you re-type 100 into the input box? If it doesn't work I'll add a fallback value.

It doesn't work。

**Comment by AnubisNekhet** [comment]
I see. I've pushed an update for the theme which adds a fallback value for the table width. It should work if you enable custom table width. If it doesn't work, I'll put it on my priority list to overhaul tables.

**Comment by Yaozhuwa** [comment]
I update theme to 1.0.5, reload obsidian, and re-set style setting as below, It still not work.
<img width="780" alt="image" src="https://user-images.githubusercontent.com/28787183/197449951-2ea0a97c-ee08-4913-b728-232c24e7315d.png">

**Comment by AnubisNekhet** [comment]
Ah, my bad 😅 I'm very sorry. I made a major mistake in the code which broke the table styling. It should 100% work now, I'm really sorry for the inconvenience.

**Comment by AnubisNekhet** [comment]
Please update to 1.0.6, it 100% should work now.

**Comment by Yaozhuwa** [comment]
Yes, it works in 1.0.6!

**Comment by Yaozhuwa** [comment]
Thank you for your awesome theme!
