### ISSUE TITLE
[Bug] Auto-hide tab title bar function when active is overlapping Minimize, Maximize and Close buttons

### ISSUE THREAD

**Issue by darkmarcos** [AnubisNekhet/AnuPpuccin#69]
**Describe the bug**
[Bug] Auto-hide tab title bar function when active is overlapping Minimize, Maximize and Close buttons

**To Reproduce**
1. Go to Style Settings pluggin options > General UI
2. Enable Auto-hide tab title bar
3. Try to click on Minimize, Maximize and Close buttons in different scenarios

**Expected behavior**
It is expected that you will be able to click on the buttons without major difficulties.

**Comment by AnubisNekhet** [comment]
Could you send screenshots of said bug? I cannot reproduce this error.

**Comment by darkmarcos** [comment]
Sorry about low quality.

https://user-images.githubusercontent.com/87239997/216449416-22ca081e-fb58-4215-ab3f-43f4dd94faf7.mp4

**Comment by AnubisNekhet** [comment]
I've pushed out a fix for this, please let me know if it works or not.

**Comment by darkmarcos** [comment]
> I've pushed out a fix for this, please let me know if it works or not.

Yes, it worked!!

But I've noticed that the issue is still affecting other elements of "workspace-tab-header-container".

Minimize, maximize and close buttons working perfectly, but in some pixels "expand" buttom doesn't work. Same happens with "tab-list" buttom and "tab-header".

Watch the video I've recorded

https://user-images.githubusercontent.com/87239997/216579336-9653c852-7a65-4993-b5f5-424ba49d57bf.mp4

**Comment by AnubisNekhet** [comment]
I see, no problem. I'll fix said values and add a slider for further adjustment.
By the way, do you have any other snippets enabled? If you do, please disable them and see if the issue still persists.

**Comment by AnubisNekhet** [comment]
The latest commit adds a variable called `--title-bar-windows-fix` which accepts any integer.
This should fix most of your problems:
```css
body.anp-autohide-titlebar:not(.is-mobile) {
   --title-bar-windows-fix: 5;
}
```

**Comment by darkmarcos** [comment]
It worked great!!

But part of "workspace-tab-header-container" is still with the issue.

![image](https://user-images.githubusercontent.com/87239997/216611406-b4aa7b6b-4dcb-443b-850e-341c312d9f1a.png)

On the other hand, it seems that minimize, maximize and close buttons are back to square one.

https://user-images.githubusercontent.com/87239997/216612005-ce1125e3-c68e-4cc3-8614-bfe41f03117d.mp4

**Comment by AnubisNekhet** [comment]
> ```css
> body.anp-autohide-titlebar:not(.is-mobile) {
>    --title-bar-windows-fix: 5;
> }
> ```

Did you try using this snippet? If not, then I think it should solve the issue.

**Comment by darkmarcos** [comment]
I forgot to try using the snippet 🫢.

With the snippet active, only remains what i've indicated as "part of 'workspace-tab-header-container' with the issue" in the left corner.

![image](https://user-images.githubusercontent.com/87239997/216611406-b4aa7b6b-4dcb-443b-850e-341c312d9f1a.png)

**Comment by AnubisNekhet** [comment]
I see.

**Comment by AnubisNekhet** [comment]
I've pushed an update which should fix that final part as well.
